create table if not exists public.items (
  id bigint generated by default as identity primary key,
  title text not null,
  description text default '',
  status text not null default 'pending' check (status in ('pending', 'progress', 'done')),
  image_url text,
  created_at timestamptz not null default now()
);

alter table public.items
add column if not exists image_url text;

alter table public.items enable row level security;

drop policy if exists "Allow public read items" on public.items;
create policy "Allow public read items"
on public.items for select
to anon
using (true);

drop policy if exists "Allow public insert items" on public.items;
create policy "Allow public insert items"
on public.items for insert
to anon
with check (true);

drop policy if exists "Allow public update items" on public.items;
create policy "Allow public update items"
on public.items for update
to anon
using (true)
with check (true);

drop policy if exists "Allow public delete items" on public.items;
create policy "Allow public delete items"
on public.items for delete
to anon
using (true);

insert into storage.buckets (id, name, public)
values ('item-images', 'item-images', true)
on conflict (id) do update set public = true;

drop policy if exists "Allow public read item images" on storage.objects;
create policy "Allow public read item images"
on storage.objects for select
to anon
using (bucket_id = 'item-images');

drop policy if exists "Allow public upload item images" on storage.objects;
create policy "Allow public upload item images"
on storage.objects for insert
to anon
with check (bucket_id = 'item-images');

drop policy if exists "Allow public update item images" on storage.objects;
create policy "Allow public update item images"
on storage.objects for update
to anon
using (bucket_id = 'item-images')
with check (bucket_id = 'item-images');
